openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: App for saving contacts
tags:
  - name: Contacts
    description: Operations about users
  - name: Authentication
    description: Authentication operations
servers:
  - url: http://localhost:3000
  - url: https://swagger-docs-vtnn.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml

  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml
    patch:
      $ref: ../swagger/paths/contacts/{contactId}/patch.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/authentication/login.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/authentication/refresh.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/authentication/register.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/authentication/logout.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/authentication/resetPassword.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/authentication/sendResetEmail.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
